# Generated by Django 5.1.4 on 2026-10-07 02:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(7)])),
                ('premature_birth', models.BooleanField(default=False)),
                ('lifting_head_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('rolling_over_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('sitting_up_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('crawling_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('standing_with_support_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('standing_individually_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_sugar_mg_dl', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)])),
                ('previous_abortions', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('bmi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)])),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(260)])),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(160)])),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy', to='patients.patient')),
            ],
        ),
    ]
