# Generated by Django 5.1.4 on 2026-10-09 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_birthmilestones_pregnancyhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_on', models.DateField()),
                ('age_years', models.FloatField(help_text='Age at assessment, derived from date of birth.')),
                ('age_group', models.CharField(max_length=8)),
                ('iq_test_type', models.CharField(blank=True, choices=[('WASI', 'WASI - Wechsler Abbreviated Scale of Intelligence'), ('WAIS', 'WAIS - Wechsler Adult Intelligence Scale'), ('WISC', 'WISC - Wechsler Intelligence Scale for Children'), ('OTHER', 'Other instrument')], max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('fiq', models.SmallIntegerField(blank=True, null=True)),
                ('viq', models.SmallIntegerField(blank=True, null=True)),
                ('piq', models.SmallIntegerField(blank=True, null=True)),
                ('ados_total', models.SmallIntegerField(blank=True, null=True)),
                ('ados_comm', models.SmallIntegerField(blank=True, null=True)),
                ('ados_social', models.SmallIntegerField(blank=True, null=True)),
                ('ados_stereo_behav', models.SmallIntegerField(blank=True, null=True)),
                ('srs_raw_total', models.SmallIntegerField(blank=True, null=True)),
                ('aq_total', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_code', models.PositiveSmallIntegerField(help_text='Dataset coding: 1 = autism, 2 = control')),
                ('probability_autism', models.FloatField()),
                ('probability_control', models.FloatField()),
                ('outcome', models.CharField(choices=[('likely_asd', 'Higher likelihood of ASD'), ('unlikely_asd', 'Lower likelihood of ASD'), ('inconclusive', 'Inconclusive')], max_length=16)),
                ('model_version', models.CharField(max_length=64)),
                ('features', models.JSONField(help_text='Exact feature vector given to the model')),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='assessments.assessment')),
            ],
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['patient', '-created_at'], name='assessments_patient_44c14c_idx'),
        ),
    ]
